### ISSUE TITLE
Scroll bar coming next to your name

### ISSUE THREAD

**Issue by ishit-07** [ugistelmokaitis/charm#80]
<img src="https://user-images.githubusercontent.com/75534993/219454810-0061db09-3a0d-4ce8-a580-56bb4bfdb64f.png" height=300px width=500px>

**Comment by ishit-07** [comment]
If you remove the line height from your name then it will be fine.

**Comment by ugistelmokaitis** [comment]
Hey Buddy,

Cheers for finding a bug. Unfortunately I need to void this as I'm already working on my new website which is 2x more advance, with design and logic itself :)
